config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  get 'welcome/contact'
  get 'welcome/admin'
  
  root 'welcome#index'

  resources :teams do
    get 'logos', on: :collection
  end
  
  
  resources :players do
    get 'not_picked', on: :collection
    get 'admin_index', on: :collection
    get "positions/:position", on: :collection, to: "players#position", as: :position
  end
  
  
  
  resources :ownerships do
    get 'last_three', on: :collection
    get 'results', on: :collection
    get "rounds/:round", on: :collection,  to: "ownerships#round", as: :round
    
  end
  
  get 'team/:id/remove_logo', to: 'teams#remove_logo', as: 'remove_team_logo' 
  

end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
  belongs_to :player
  belongs_to :team
  
  validates :round, :pick, :team_id, presence: true
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_one :team, through: :ownership
  has_one :ownership
  
  validates :name, presence: true
  validates :surname, presence: true
  validates :position, presence: true
  
  def full_name
    "#{name} #{surname}"
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :ownerships
  has_many :players, through: :ownerships 
  
  validates :name, presence: true

  validates :division, presence: true

  has_attached_file :logo , :styles => { :small => '10>', :medium => '40>', :large => '60>' }
  validates_attachment_content_type :logo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
 



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController
  
  def index
    @ownerships = Ownership.where(player_id: nil) 
    #Ineffcient ruby eqivalent: Ownership.all.select { |t| t.player_id == nil}
    
    if Ownership.find_by(player_id: nil) != nil
      Rails.application.config.counter = Ownership.find_by(player_id: nil).id
    else
      Rails.application.config.counter = 500
    end
  end

  def results
    @ownerships = Ownership.where.not(player_id: nil)
  end
  
  def round
    @ownerships = Ownership.where(round: params[:round])
  end
  
  def last_three
    @ownerships = Ownership.where.not(player_id: nil).last(3) | Ownership.where(player_id: nil).first(1)
    
  end
  
  def show
    @ownership = Ownership.find(params[:id])
  end

  def edit
    @ownership = Ownership.find(params[:id])
    @players = Player.all
  end

  def update
    @ownership = Ownership.find(params[:id])
    
    if @ownership.update(ownership_params)
      
      redirect_to ownerships_path
    else
      render 'edit'
    end
  end

  private
  def ownership_params
    params.require(:ownership).permit(:round,:pick,:team_id,:player_id)
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  
  
  def index
    @players = Player.all.order(position: :asc, surname: :asc)
  end
  
  def not_picked
    #@players = Player.where(team: nil).order(position: :asc, surname: :asc)
    @players = Player.joins("LEFT OUTER JOIN ownerships ON ownerships.player_id = players.id").joins("LEFT OUTER JOIN teams ON ownerships.team_id = teams.id").where("teams.id IS NULL").order(position: :asc, surname: :asc)
  end
  
  def admin_index
    @players = Player.all
  end
  
  def position
    @players = Player.where(position: params[:position]).order(surname: :asc)
  end
  
  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    
    if @player.update(player_params)
      redirect_to admin_index_players_path
    else
      render 'edit'
    end
  end


private

def player_params
  params.require(:player).permit(:name, :surname, :position)
end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  
  def index
    @teams = Team.all
  end

  def remove_logo 
    @team = Team.find(params[:id])
    @team.logo = nil
    @team.save
    redirect_to @team
  end
  
  def logos
    @teams = Team.all
  end
  
  def edit
    @team = Team.find(params[:id])
  end
  
  def show
    @team = Team.find(params[:id])
    @players = @team.players
  end
  
  def update
    @team = Team.find(params[:id])
    
    if @team.update(team_params)
      redirect_to logos_teams_path
    else
      render 'edit'
    end
  end
  
  
  
  
  private
  def team_params
    params.require(:team).permit(:name, :logo, :division)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 
  
  
  def index
  end
  
  def contact
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nfldraft</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ownerships/_ownmenu.html.erb
<nav class="mininav">
<ul>
	<li class="start"><li><%= link_to 'Draft Home', ownerships_path %></li></li>
	<li><%= link_to 'Last 3 Picks', last_three_ownerships_path %> </li>
	<li><%= link_to 'Full Results', results_ownerships_path %></li>
	<li><%= link_to 'Round 1', round_ownerships_path(round: 1) %></li>
	<li><%= link_to 'Round 2', round_ownerships_path(round: 2) %></li>
	<li><%= link_to 'Round 3', round_ownerships_path(round: 3) %></li>
	<li><%= link_to 'Round 4', round_ownerships_path(round: 4) %></li>
	<li><%= link_to 'Round 5', round_ownerships_path(round: 5) %></li>
	<li><%= link_to 'Round 6', round_ownerships_path(round: 6) %></li>
	<li><%= link_to 'Round 7', round_ownerships_path(round: 7) %></li>
	
	
  <li class="end">

</li>
</ul>
</nav>

app/views/ownerships/edit.html.erb
<%= render 'welcome/menu' %>


<div class="left">
<br>
   <%= form_for @ownership do |f| %>
<p>
   Round <%= @ownership.round %> of the NFL draft.
 
 <br>
   <% if @ownership.team.logo_file_name == nil %>

<% else %>	
	 <%= image_tag @ownership.team.logo(:large) %>
<% end %>
 
 <p>
    The  <%= @ownership.team.name %>'s pick is:
 <br>

<%= f.collection_select(:player_id, Player.joins("LEFT OUTER JOIN ownerships ON ownerships.player_id = players.id").joins("LEFT OUTER JOIN teams ON ownerships.team_id = teams.id").where("teams.id IS NULL").order(surname: :asc), :id, :full_name)%>	
 <br>

<%= f.submit "Select Player"%>
</p>

<% end %>
</div>

app/views/ownerships/index.html.erb
<%= render 'welcome/menu' %>
<%= render 'ownmenu' %>



<table id="tblMain" class="table1">

  <thead>
    <tr>
      <th><h2>Draft
	  <% if Rails.application.config.counter == 500 %>
	  Finished!
	  <% else %>
	  <% end %>
	  </h2></th>
	  <th>Round</th>
      <th>Pick Number</th>
      <th></th>  
	  <th>Team Name</th>
     
      <th>Player</th>
	  <th>Select Player</th>
    </tr>
  </thead>
  <tbody>
    <% @ownerships.each do |ownership| %>
      <tr>
      <td></td>
        <td><%= ownership.round %></td>
        <td><%= ownership.pick %></td>
        <% if ownership.team.logo_file_name == nil %>
		<td></td>
		<% else %>	
			<td><%= image_tag ownership.team.logo.url(:medium) %></td>
		<% end %>
		<td><%= ownership.team.name %></td> 
       
		<% if ownership.player_id == nil %>
		<td>No pick yet</td>
		<% else %>
		<td><%= ownership.player.name %></td>
		<% end %>
		<% if ownership.pick == (Rails.application.config.counter) %>
		<td><%= link_to 'Select Player', edit_ownership_path(ownership) %></td> 
		<% else %>
		
		<td>Pending</td>
		
		<% end %>
        </tr>
		
		<script type="text/javascript">
			   rows()
		</script>
		
    <% end %>
  </tbody>
</table>

app/views/ownerships/last_three.html.erb
<%= render 'welcome/menu' %>
<%= render 'ownmenu' %>



<table class="table1">

  <thead>
    <tr>
      <th><h2>Last Three Picks</h2></th>
       <th></th>
	  <th>Round</th>
      <th>Pick Number</th>
      <th></th>
	  <th>Team</th>
      <th>Player</th>
	 
    </tr>
  </thead>
  <tbody>
    <% @ownerships.each do |ownership| %>
      <tr>
      <% if ownership.pick == Rails.application.config.counter %>
 	  <th>NEXT PICK !</th>
 	  <% else %>
 	  <td></td>
 	  <% end %>
	  
	  <td></td>
		<td><%= ownership.round %></td>
        <td><%= ownership.pick %></td>
        <% if ownership.team.logo_file_name == nil %>
		<td></td>
		<% else %>	
			<td><%= image_tag ownership.team.logo.url(:medium) %></td>
		<% end %>
		<td><%= ownership.team.name %></td> 
      
	     <% if ownership.player_id == nil %>
	    <td>Pending</td>
	    <% else %>
	    <td><%= ownership.player.full_name %></td>
	    <% end %>
		
	  </tr>
    <% end %>
  </tbody>
</table>

app/views/ownerships/results.html.erb
<%= render 'welcome/menu' %>
<%= render 'ownmenu' %>

<table id="tblMain" class="table1">

  <thead>
    <tr>
      <th><h2>Draft Results</h2></th>
      <th>Round</th>
      <th>Pick Number</th>
      <th></th>
	  <th>Team</th>
      <th>Player</th>
	 
    </tr>
  </thead>
  <tbody>
    <% @ownerships.each do |ownership| %>
      <tr>
      <td></td>
        <td><%= ownership.round %></td>
        <td><%= ownership.pick %></td>
        <% if ownership.team.logo_file_name == nil %>
		<td></td>
		<% else %>	
			<td><%= image_tag ownership.team.logo.url(:medium) %></td>
		<% end %>
		<td><%= ownership.team.name %></td> 
      
	     <% if ownership.player_id == nil %>
	
	    <% else %>
	    <td><%= ownership.player.full_name %></td>
	    <% end %>
	  </tr>
  	<script type="text/javascript">
  		   rows()
  	</script>
	  
    <% end %>
  </tbody>
</table>

app/views/ownerships/round.html.erb
<%= render 'welcome/menu' %>
<%= render 'ownmenu' %>

<table id="tblMain" class="table1">

  <thead>
    <tr>
      <th><h2>Round Results</h2></th>
      <th>Round</th>
      <th>Pick Number</th>
      <th></th>
	  <th>Team</th>
      <th>Player</th>
	 
    </tr>
  </thead>
  <tbody>
    <% @ownerships.each do |ownership| %>
      <tr>
      <td></td>
        <td><%= ownership.round %></td>
        <td><%= ownership.pick %></td>
        <% if ownership.team.logo_file_name == nil %>
		<td></td>
		<% else %>	
			<td><%= image_tag ownership.team.logo.url(:medium) %></td>
		<% end %>
		<td><%= ownership.team.name %></td> 
      
	     <% if ownership.player_id == nil %>
	   <td>Pending</td>
	    <% else %>
	    <td><%= ownership.player.full_name %></td>
	    <% end %>
		
	  </tr>
    
	<script type="text/javascript">
		   rows()
	</script>
	
	<% end %>
  </tbody>
</table>

app/views/players/_player_menu.html.erb
<nav class="mininav">
<ul>
	<li class="start"><li><%= link_to 'Players', players_path %></li>
	<li><%= link_to 'Undrafted Players', not_picked_players_path %></li>
	<li><%= link_to 'Players by Position', position_players_path(position: 'QB') %></li>
	
	
	
  <li class="end">

</li>
</ul>
</nav>

app/views/players/_player_positions.html.erb
<nav class="mininav">
<ul>
	<li><%= link_to 'QB', position_players_path(position: 'QB') %></li>
	<li><%= link_to 'C', position_players_path(position: 'C') %></li>
	<li><%= link_to 'CB', position_players_path(position: 'CB') %></li>
	<li><%= link_to 'DE', position_players_path(position: 'DE') %></li>
	<li><%= link_to 'DT', position_players_path(position: 'DT') %></li>
	<li><%= link_to 'FB', position_players_path(position: 'FB') %></li>
	<li><%= link_to 'FS', position_players_path(position: 'FS') %></li>
	<li><%= link_to 'ILB', position_players_path(position: 'ILB') %></li>
	<li><%= link_to 'K', position_players_path(position: 'K') %></li>
	<li><%= link_to 'LS', position_players_path(position: 'LS') %></li>
	<li><%= link_to 'OG', position_players_path(position: 'OG') %></li>
	<li><%= link_to 'OLB', position_players_path(position: 'OLB') %></li>
    <li><%= link_to 'OT', position_players_path(position: 'OT') %></li>
	<li><%= link_to 'P', position_players_path(position: 'P') %></li>
	<li><%= link_to 'RB', position_players_path(position: 'RB') %></li>
	<li><%= link_to 'SS', position_players_path(position: 'SS') %></li>
	<li><%= link_to 'TE', position_players_path(position: 'TE') %></li>
	<li><%= link_to 'WR', position_players_path(position: 'WR') %></li>
</ul>
</nav>

app/views/players/admin_index.html.erb
<%= render 'welcome/menu' %>
<%= render 'welcome/admin_menu' %>


<table id="tblMain" class="table1">
  <thead>
    <tr>
    <th><h2>All Players</h2></th>
      <th>Name</th>
      <th>Position</th>
      <th>Team</th>
      <th>Edit</th>
	</tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
       <tr>
       <td></td>
        <td><%= player.full_name %></td>
		<td><%= player.position %></td>
        <td><%= player.try(:team).try(:name) %> </td> 
  	    <td><%= link_to "Edit Player", edit_player_path(player) %>
		
		<script type="text/javascript">
			   rows()
		</script>
  
  
  <%end%>
  </tbody>
</table>

app/views/players/edit.html.erb
<%= render 'welcome/menu' %>

<div class="left">

<%= form_for @player do |f| %>
  <p>
    <%= f.label 'First Name' %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label 'Last Name' %><br>
    <%= f.text_field :surname %>
  </p>
  
  <p>
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back to Players List', admin_index_players_path %>

</div>

app/views/players/index.html.erb
<%= render 'welcome/menu' %>
<%= render 'player_menu' %>


<table id="tblMain" class="table1">
  <thead>
    <tr>
    <th><h2>All Players</h2></th>
      <th>Name</th>
      <th>Position</th>
      <th>Team</th>
      <th></th>
	</tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
       <tr>
       <td></td>
        <td><%= player.full_name %></td>
		<td><%= player.position %></td>
        <td><%= player.try(:team).try(:name) %> </td> 
  	    
		<% if player.try(:team).try(:logo_file_name) == nil %>
  	  <td></td>
  	  <% else %>
		<td><%= image_tag player.try(:team).try(:logo).try(:url, :medium) %> </td>
      <% end %>
	  </tr>
    
	<script type="text/javascript">
		   rows()
	</script>
	
	
	<% end %>
  </tbody>
</table>

app/views/players/not_picked.html.erb
<%= render 'welcome/menu' %>
<%= render 'player_menu' %>



<table id="tblMain" class="table1">
  <thead>
    <tr>
    <th><h2>Undrafted Players</h2></th>
      <th>Name</th>
      <th>Position</th>
      
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
       <tr>
       <td></td>
       <td><%= player.full_name %></td>
       <td><%= player.position %></td>
       </tr>
    
	<script type="text/javascript">
		   rows()
	</script>
	
	
	<% end %>
  </tbody>
</table>

app/views/players/position.html.erb
<%= render 'welcome/menu' %>
<%= render 'player_menu' %>
<%= render 'player_positions' %>



<table id="tblMain" class="table1">
  <thead>
    <tr>
    <th></th>
      <th>Name</th>
      <th>Team</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
       <tr>
       
	  
          <td><%= player.name %> <%= player.surname %></td>
	      <td><%= player.try(:team).try(:name) %> </td> 
  	    
		  <% if player.try(:team).try(:logo_file_name) == nil %>
	  	    <td></td>
	  	    <% else %>
		   <td><%= image_tag player.try(:team).try(:logo).try(:url, :medium) %> </td>
	      <% end %>
		  </tr>
		  
	  	<script type="text/javascript">
	  		   rows()
	  	</script>
	  
    <% end %>
  </tbody>
</table>

app/views/welcome/_admin_menu.html.erb
<nav class="mininav">
<ul>
  <li class="start"><%= link_to 'Team Administration', logos_teams_path %></li>
  <li><%= link_to 'Player Administration', admin_index_players_path %></li>
 
  <li class="end">

</li>
</ul>
</nav>

app/views/welcome/_menu.html.erb
<header>
<h1>NFL Draft</h1>

<h2>THE HISTORY OF THE GRIDIRON STARTS HERE</h2>

</header>

<nav>
<ul>
	<li class="start"><%= link_to 'Home', welcome_index_path %></li>
	<li><%= link_to 'Teams', teams_path %> </li>
	<li><%= link_to 'Players', players_path %></li>
	<li><%= link_to 'Draft', ownerships_path %></li>
    <li><%= link_to 'Administration', welcome_admin_path %></li>
    <li><%= link_to 'Contact', welcome_contact_path %></li>
  <li class="end">

</li>
</ul>
</nav>

app/views/welcome/admin.html.erb
<%= render 'welcome/menu' %>
<%= render 'welcome/admin_menu' %>



<div style="margin-left:auto;margin-right:auto;width:960px;">
	<%= image_tag('draftadmin1.jpg')%>
</div>	

app/views/welcome/contact.html.erb
<%= render 'welcome/menu' %>

<div class="center">
	<%= image_tag('1960contact.jpg')%>
</div>	

app/views/welcome/index.html.erb
<%= render 'welcome/menu' %>



<div style="margin-left:auto;margin-right:auto;width:960px;">
	<%= image_tag('1960.jpg')%>
</div>	